api/urls.py
from django.urls import path

from .views import KAMAR_check

urlpatterns = [
    path("check/", KAMAR_check, name="check"),
]

commendationSite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path("api/", include("api.urls")),
    path("login/", RedirectView.as_view(url="/users/login/", permanent=True)),
    path("logout/", RedirectView.as_view(url="/users/logout/", permanent=True)),
    path("users/", include("users.urls")),
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("commendations/", include("commendations.urls")),
    path("students/", include("students.urls")),
    path("", include("home.urls")),
]

# Set admin site titles
admin.site.site_header = "Bayfield Commendations Administration"
admin.site.site_title = "Bayfield Commendations Admin Portal"
admin.site.index_title = "Welcome to Bayfield's Commendation Site Admin Portal"

# Custom error views
handler403 = "home.views_errors.error_403"
handler404 = "home.views_errors.error_404"
handler500 = "home.views_errors.error_500"

commendations/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("award/", views.giveCommendation, name="giveCommendation"),
    path("spirit/", views.awardMilestones, name="viewMilestones"),
    path("my/", views.myCommendations, name="myCommendations"),
    path(
        "detail/<int:commendation_id>/",
        views.commendationDetail,
        name="commendationDetail",
    ),
    path("progress/", views.milestoneProgress, name="milestoneProgress"),
]

commendations/models.py
from django.db import models

# Create your models here.


class Commendation(models.Model):
    """
    The model for commendations.

    This model stores data for the commendations that have been awarded to students by teachers.

    Related Models:
        * :model:`users.User` - The user model that is linked to the Student/Teacher
        * :model:`teachers.Teacher` - The teacher model that is linked to the Teacher that awarded the commendation
        * :model:`students.Student` - The student model that is linked to the Student that was awarded the commendation

    Fields:
        * id (AutoField): The primary key of the commendation
        * commendation_type (str): The type of commendation that was awarded
        * reason (str): The reason for the commendation
        * date_time (DateTimeField): The date and time the commendation was awarded
        * teacher (ForeignKey): The teacher model that is linked to the Teacher that awarded the commendation
        * student (ManyToManyField): The student model that is linked to the Student that was awarded the commendation

    Docs updated on: 30/7/2022
    """

    # Unique id for commendations
    id = models.AutoField(
        primary_key=True,
        unique=True,
        editable=False,
        blank=False,
        null=False,
        verbose_name="ID",
    )

    # The type of commendation given
    RESPECT = "R"
    INTEGRITY = "I"
    SERVICE = "S"
    EXCELLENCE = "E"
    OTHER = "O"
    COMMENDATION_TYPE_CHOICES = (
        (RESPECT, "Respect"),
        (INTEGRITY, "Integrity"),
        (SERVICE, "Service"),
        (EXCELLENCE, "Excellence"),
        (OTHER, "Other"),
    )
    commendation_type = models.CharField(
        max_length=1,
        choices=COMMENDATION_TYPE_CHOICES,
        blank=False,
        null=False,
        verbose_name="Commendation Type",
    )

    # Inside/outside of classroom
    INSIDE = "I"
    OUTSIDE = "O"
    EXTRACURRICULAR = "E"
    INSIDE_OUTSIDE_CHOICES = (
        (INSIDE, "In class"),
        (OUTSIDE, "Out of class"),
        (EXTRACURRICULAR, "Extracurricular"),
    )
    inside_outside = models.CharField(
        max_length=1,
        choices=INSIDE_OUTSIDE_CHOICES,
        blank=False,
        null=False,
        default=INSIDE,
        verbose_name="Commendation Location",
    )

    # The reason for giving the commendation
    reason = models.TextField(
        max_length=500, blank=False, null=False, verbose_name="Reason"
    )

    # The date and time the commendation was given
    date_time = models.DateTimeField(
        blank=False, null=False, verbose_name="Date and Time given", auto_now_add=True
    )

    # The teacher who gave the commendation
    teacher = models.ForeignKey(
        "teachers.teacher",
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        verbose_name="Teacher",
    )

    # The student(s) who received the commendation
    students = models.ManyToManyField(
        "students.student", blank=False, verbose_name="Students"
    )

    class Meta:
        """Meta settings for model"""

        verbose_name = "Commendation"
        verbose_name_plural = "Commendations"

    def __str__(self) -> str:
        return f"Commendation ID: {self.id}"


class Milestone(models.Model):
    """
    The model for commendation Milestones.

    This model stores data for the milestones for numbers of commendations awarded to students.

    Related Models:
        * :model:`users.User` - The user model that is linked to the Student/Teacher
        * :model:`students.Student` - The student model of the student who received the milestone award

    Fields:
        * id (AutoField): The primary key of the commendation
        * milestone_type (int): The type of commendation that was awarded - based on the number of commendations given
        * date_time (DateTimeField): The date and time the commendation was awarded
        * student (ForeignKey): The student who received the milestone award

    Docs updated on: 12/8/2022
    """

    # Unique id for milestones
    id = models.AutoField(
        primary_key=True,
        unique=True,
        editable=False,
        blank=False,
        null=False,
        verbose_name="ID",
    )

    # The type of milestone
    CERTIFICATE = 25
    GREEN = 50
    BLUE = 100
    GOLD = 150
    MILESTONE_TYPE_CHOICES = (
        (CERTIFICATE, f"Dean's Certificate for {CERTIFICATE} commendations"),
        (GREEN, f"Green Jr School spirit badge for {GREEN} commendations"),
        (BLUE, f"Blue Jr School spirit badge for {BLUE} commendations"),
        (GOLD, f"Gold Jr School spirit badge for {GOLD} commendations"),
    )
    milestone_type = models.IntegerField(
        choices=MILESTONE_TYPE_CHOICES,
        blank=False,
        null=False,
        verbose_name="Milestone Type",
    )

    # The date and time the milestone was given
    date_time = models.DateTimeField(
        blank=False, null=False, verbose_name="Date and Time given", auto_now_add=True
    )

    # The student(s) who received the milestone
    student = models.ForeignKey(
        "students.student",
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        verbose_name="Student",
    )

    # Has the milestone been awarded?
    awarded = models.BooleanField(
        default=False, blank=False, null=False, verbose_name="Awarded"
    )

    class Meta:
        """Meta settings for model"""

        verbose_name = "Milestone"
        verbose_name_plural = "Milestones"

    def __str__(self) -> str:
        milestone_type = [
            choice[1]
            for choice in Milestone.MILESTONE_TYPE_CHOICES
            if choice[0] == self.milestone_type
        ][0]
        return f"{milestone_type} - {self.student}"

    def prettyPrint(self) -> str:
        """Pretty print the milestone type."""
        milestone_type = [
            choice[1]
            for choice in Milestone.MILESTONE_TYPE_CHOICES
            if choice[0] == self.milestone_type
        ][0]
        return milestone_type

commendations/views.py
from datetime import datetime

from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.http import Http404
from django.shortcuts import redirect, render
from django.utils.timezone import make_aware

from commendationSite.authHelper import get_student, role_required
from students.models import Student
from teachers.models import Teacher

from .models import Commendation, Milestone

# Create your views here.


@role_required(teacher=True)
def giveCommendation(request):
    """Award commendations to students."""
    if request.method == "POST":
        commendationType = request.POST["commendationType"]

        # Reason processing
        quickReason = request.POST["quickReason"]
        reason = request.POST["reason"]

        if quickReason == "" and reason == "":
            reason = "No reason given"

        elif quickReason != "" and reason == "":
            reason = quickReason

        elif quickReason != "" and reason != "":
            reason = f"{quickReason}: {reason}"

        rawStudents = request.POST["selectedStudents"]
        # Split the students into a list
        students = rawStudents.split(",")
        # Remove any empty strings, duplicates, convert to ints and remove non-existent students
        students = list(set(filter(lambda student: student != "", students)))
        students = list(map(lambda student: int(student), students))
        students = list(
            filter(lambda student: Student.objects.filter(id=student), students)
        )

        # If no students were selected, return an error
        if len(students) == 0:
            messages.error(request, "No students were selected")
            return redirect("/commendations/award/")

        # Get the teacher that is awarding the commendation
        teacher = Teacher.objects.get(id=request.POST["teacher"])

        # Create a new commendation for the student(s)
        commendation = Commendation(
            teacher=teacher,
            reason=reason,
            commendation_type=commendationType,
        )
        # Must save the commendation before adding students
        commendation.save()

        # Add the students to the commendation
        for student in students:
            student = Student.objects.get(id=student)
            commendation.students.add(student)

        # Save the commendation
        commendation.save()

        # Check each student for a milestone
        for student in students:
            student = Student.objects.get(id=student)
            for milestoneType in Milestone.MILESTONE_TYPE_CHOICES:
                # Get the int value of the milestone type
                milestoneValue = milestoneType[0]
                # Check if the student has now met the milestone number of commendations
                if student.commendation_set.count() == milestoneValue:
                    # Create a milestone for the student
                    milestone = Milestone(
                        student=student, milestone_type=milestoneValue
                    )
                    milestone.save()

                    # Inform the teacher that the student has met the milestone
                    messages.add_message(
                        request,
                        messages.SUCCESS,
                        f"{student} has enough commendations to reach a {milestoneType[1]}! This will be awarded automatically.",
                    )

        # Message the user
        messages.add_message(
            request,
            messages.SUCCESS,
            f"Commendation awarded to {len(students)} students!",
        )

        return redirect("/commendations/award/")

    # Process and render the award commendation page
    _commendationTypes = []
    _commendationLocations = []

    for Type in Commendation.COMMENDATION_TYPE_CHOICES:
        _commendationTypes.append({"name": Type[1], "value": Type[0]})
    for Location in Commendation.INSIDE_OUTSIDE_CHOICES:
        _commendationLocations.append({"name": Location[1], "value": Location[0]})

    # If there is a teacher signed in, then the only teacher that should show is themselves
    teachers = Teacher.objects.filter(user=request.user)

    # Filter students to year 9 and 10 only
    students = Student.objects.filter(year_level__in=[9, 10])

    # Generate context and render the page
    context = {
        "commendationTypes": _commendationTypes,
        "commendationLocations": _commendationLocations,
        "students": students,
        "teachers": teachers,
    }

    return render(request, "commendations/award.html", context)


@role_required(teacher=True, management=True)
def awardMilestones(request):
    """The page where teachers can award milestones"""
    if request.method == "POST":
        # there will be a list of milestone IDs
        milestoneIDs = request.POST.getlist("milestone")

        # Get the milestone objects
        milestones = Milestone.objects.filter(id__in=milestoneIDs)

        # Remove any that have already been awarded
        milestones = milestones.filter(awarded=False)
        # If milestones were removed for being awarded, inform the user
        if len(milestones) != len(milestoneIDs):
            messages.warning(
                request,
                "Some milestones have not been changed as they were already marked as awarded",
            )

        # If there are no milestones
        if len(milestones) == 0:
            messages.warning(
                request, "No milestones were awarded as no valid ones were selected"
            )
            return redirect("/commendations/spirit/")

        # Mark the milestones as awarded
        for milestone in milestones:
            milestone.awarded = True
            milestone.save()

        messages.success(request, f"Marked {len(milestones)} milestones as awarded")
        return redirect("/teachers/")

    # Get all milestones
    milestoneTypes = Milestone.MILESTONE_TYPE_CHOICES
    milestones = Milestone.objects.all()

    # Filter dates
    dateQuery = request.GET.get("date")
    if dateQuery:
        # Convert the date to a datetime object
        date = make_aware(datetime.strptime(dateQuery, "%Y-%m-%d"))
        milestones = milestones.filter(date_time__gte=date)

    # Filter by type
    milestoneTypeQuery = request.GET.getlist("type")
    if milestoneTypeQuery:
        milestones = milestones.filter(milestone_type__in=milestoneTypeQuery)

    # Sort by the type then by student name
    milestones = milestones.order_by(
        "awarded",
        "milestone_type",
        "student__user__first_name",
        "student__user__last_name",
    )

    # Untupple the milestone types
    milestoneTypes = [
        {"value": milestoneType[0], "name": milestoneType[1]}
        for milestoneType in milestoneTypes
    ]

    # If no filters are applied, return no milestones
    if not milestoneTypeQuery and not dateQuery:
        milestones = []

    # return the page
    return render(
        request,
        "commendations/award_milestones.html",
        {"milestones": milestones, "milestoneTypes": milestoneTypes},
    )


@role_required(student=True, caregiver=True)
@get_student()
def myCommendations(request, student: Student = None):
    commendations = student.commendation_set.all().order_by("-date_time")
    commendationsSinceLastLogin = commendations.filter(
        date_time__gte=request.user.previous_login or request.user.last_login
    )

    return render(
        request,
        "commendations/my_commendations.html",
        {
            "commendations": commendations,
            "studentSwitcherEnabled": True,
            "commendationsSince": commendationsSinceLastLogin,
            "student": student,
        },
    )


@role_required(student=True, caregiver=True)
@get_student()
def commendationDetail(request, commendation_id, student: Student = None):
    """The page where students can view the details of a commendation"""
    try:
        commendation = Commendation.objects.get(id=commendation_id)
    except Commendation.DoesNotExist:
        raise Http404("Commendation does not exist")

    # Check if the student is in the commendation
    if student not in commendation.students.all():
        raise PermissionDenied

    return render(
        request,
        "commendations/detailed_commendation.html",
        {
            "commendation": commendation,
            "student": student,
        },
    )


@role_required(student=True, caregiver=True)
@get_student()
def milestoneProgress(request, student: Student = None):
    """The page where students can view their progress towards milestones"""
    milestones = Milestone.objects.filter(student=student).order_by("-milestone_type")
    commendations = student.commendation_set.all().order_by("-date_time")
    # For each milestone type, calculate the progress as a percentage
    progress = []
    for milestoneType in Milestone.MILESTONE_TYPE_CHOICES:
        # Get the int value of the milestone type
        milestoneValue = milestoneType[0]
        # Get the number of commendations the student has
        commendationCount = commendations.count()
        # Calculate the percentage
        percentage = (commendationCount / milestoneValue) * 100
        # Dont allow the percentage to be over 100
        min(percentage, 100)
        # Add the percentage to the list
        progress.append(
            {
                "type": milestoneType[1],
                "percentage": round(percentage),
                "value": round(milestoneValue),
                "remaining": round(milestoneValue - commendationCount),
            }
        )

    return render(
        request,
        "commendations/milestone_progress.html",
        {
            "milestones": milestones,
            "commendations": commendations,
            "commendationCount": commendationCount,
            "milestoneProgress": progress,
            "student": student,

commendations/templates/commendations/award.html
{% extends 'base.html' %}
{% load static %}

{% comment %} HTML title {% endcomment %}
{% block title %}Award Commendation{% endblock title %}
{% comment %} Meta description {% endcomment %}
{% block description %}Award a commendation to students who have displayed the RISE values in class{% endblock description %}

{% comment %} Content that goes in the HTML head {% endcomment %}
{% block head %}
<link rel="stylesheet" href="{% static 'commendations/giveCommendation.min.css' %}">
<script src="{% static 'commendations/search.min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script>
    {% comment %} For 2 col selector {% endcomment %}
    $(document).ready(function () {
        $('#Available').on('click', 'li', function () {
            $(this).toggleClass('selected');
            $(this).find('input').prop('checked', !$(this).find('input').prop('checked'));
            if ($(this).hasClass('selected')) {
                $('#selected-students').append('<li><input type="checkbox" id="' + $(this).find('input').attr('id') + '" checked>' + $(this).text() + '</li>');
                // Also add to hidden input
                $('#selectedStudents').val($('#selectedStudents').val() + $(this).find('input').attr('id') + ',');
            } else {
                $('#selected-students').find('#' + $(this).find('input').attr('id')).parent().remove();
                // Also remove from hidden input
                $('#selectedStudents').val($('#selectedStudents').val().replace($(this).find('input').attr('id') + ',', ''));
            }
        });
        $('#Selected').on('click', 'li', function () {
            $(this).toggleClass('selected');
            $(this).find('input').prop('checked', !$(this).find('input').prop('checked'));
            $('#selected-students').find('#' + $(this).find('input').attr('id')).parent().remove();
            // Remove selected class from li in Available
            $('#Available').find('#' + $(this).find('input').attr('id')).parent().removeClass('selected');
            // Also remove from hidden input
            $('#selectedStudents').val($('#selectedStudents').val().replace($(this).find('input').attr('id') + ',', ''));
        });
    });
</script>
{% endblock head %}

{% comment %} H1 at top of page, page title {% endcomment %}
{% block headerText %}Award Commendation{% endblock headerText %}

{% comment %} Main content {% endcomment %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="formField">
        <label for="commendationType">Commendation Type <abbr class="requiredField" title="This field is required">*</abbr></label>
        <br>
        <fieldset name="commendationType">
            {% for type in commendationTypes %}
                <input type="radio" name="commendationType" id="type-{{ type.value }}" value="{{ type.value }}" required>
                <label for="type-{{ type.value }}">{{ type.name }}</label>
                <br>
            {% endfor %}
        </fieldset>
    </div>

    <div class="formField">
        <label for="commendationLocation">Commendation Location</label>
        <br>
        <fieldset name="commendationLocation">
            {% for Location in commendationLocations %}
                {% if forloop.counter == 1 %}
                    <input type="radio" name="commendationLocation" id="loc-{{ Location.value }}" value="{{ Location.value }}" checked>
                {% else %}
                <input type="radio" name="commendationLocation" id="loc-{{ Location.value }}" value="{{ Location.value }}">
                {% endif %}
                <label for="loc-{{ Location.value }}">{{ Location.name }}</label>
                <br>
            {% endfor %}
        </fieldset>
    </div>

	<div class="formField">
		<label for="quickReason">Quick Reasons</label>
		<p class="hint">Optional. You can also enter a custom reason below</p>
		<select name="quickReason" id="quickReason">
			<option value="">No quick reason</option>
			<option value="Being Truthful">Being Truthful</option>
			<option value="Doing the right thing">Doing the right thing</option>
		</select>
	</div>

    <div class="formField">
        <label for="reason">Reason</label>
        <p class="hint">Optional. If you have selected a quick reason anything you enter here will still be included</p>
        <textarea name="reason" id="reason"></textarea>
    </div>

    <div class="formField">
        <label>Student(s) <abbr class="requiredField" title="This field is required">*</abbr></label>
        <p class="hint">Select students from the left by clicking them. Students on the right will be awarded the commendation. You can click students who are selected to deselect them</p>
        <div class="selector">
            <label id="AvailableLabel">Available Students</label>
            <label id="SelectedLabel">Selected Students</label>
            <input type="text" name="students" id="searchStudents" placeholder="Search students" onkeyup="filterStudents(this.value)">
            <div id="Available" class="selectorCol">
                <ul id="selectable-students">
                    {% for student in students %}
                        <li><input type="checkbox" id="{{student.id}}">{{student}}</li>
                    {% endfor %}
                </ul>
            </div>
            <div id="Selected" class="selectorCol">
                <ul id="selected-students">
                    <!-- Selected students will appear here -->
                </ul>
            </div>
        </div>
    </div>

    <div class="formField">
        <label for="teacher">Teacher <abbr class="requiredField" title="This field is required">*</abbr></label>
        <br>
        <select name="teacher" id="teacher" required>
            {% for teacher in teachers %}
                <option value="{{ teacher.id }}">{{ teacher }}</option>
            {% endfor %}
        </select>
    </div>

    {% comment %} Hidden selected students list {% endcomment %}
    <div class="formField">
        <input type="hidden" name="selectedStudents" id="selectedStudents">
    </div>

    <div class="formField">
        <input type="submit" value="Submit" id="submit">
    </div>
</form>
{% endblock content %}

commendations/templates/commendations/detailed_commendation.html
{% extends 'base.html' %}
{% load static %}

{% comment %} HTML title{% endcomment %}
{% block title %}Commendation Information{% endblock title %}
{% comment %} Meta description{% endcomment %}
{% block description %}Get detailed information about a Commendation{% endblock description %}


{% comment %} HTML head, for css styles etc{% endcomment %}
{% block head %}
<link rel="stylesheet" href="{% static 'commendations/certificate.min.css' %}">
<script src="https://html2canvas.hertzen.com/dist/html2canvas.min.js"></script>
<script src="{% static 'commendations/download.min.js' %}"></script>
<style>
    #cert {
        {% comment %} Place the image in the bottom right, with a small padding {% endcomment %}
        background-image: url({% static 'img/bayfield-shield-logo.png' %}) !important;
        background-position: top left !important;
        background-size: 20%  !important;
        background-repeat: no-repeat !important;
        background-origin: content-box;
    }
</style>
{% endblock head %}


{% comment %} H1 at top of page, page title{% endcomment %}


{% comment %} Main content{% endcomment %}
{% block content %}
<div class="container">
    <div id="cert">
        <div class="organisation">
            Bayfield High School
        </div>

        <div class="title">
            {{ commendation.get_commendation_type_display }} commendation
        </div>

        <div class="date">
            This commendation was awarded by {{ commendation.teacher }}, on {{ commendation.date_time|date:"F j, Y" }} to<br/>
        </div>

        <div class="person">
            {{student.user.first_name}} {{student.user.last_name}}
        </div>

        <div class="reason">
            For {{ commendation.reason }}
        </div>
    </div>
</div>
<div id="buttons">
    <a href="/">Home</a>
    <a onclick="saveCertAsPNG('#cert', '{{commendation.get_commendation_type_display}} commendation for {{student.user.first_name}} from {{commendation.teacher}}')">Save as Image</a>
    <a href="/commendations/my/">Back</a>
</div>
{% endblock content %}

commendations/templates/commendations/milestone_progress.html
{% extends 'base.html' %}
{% load static %}

{% comment %} HTML title{% endcomment %}
{% block title %}RISE award progress{% endblock title %}
{% comment %} Meta description{% endcomment %}
{% block description %}Allows students to track their progress toward RISE awards{% endblock description %}


{% comment %} HTML head, for css styles etc{% endcomment %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'commendations/milestone_progress.min.css' %}">
{% endblock head %}


{% comment %} H1 at top of page, page title{% endcomment %}
{% block headerText %}RISE award progress{% endblock headerText %}


{% comment %} Main content{% endcomment %}
{% block content %}
<h2>Your Commendations</h2>
<p>{% if request.user.is_caregiver %}{{ student.user.first_name }} has {% else %}You have{% endif %} {{ commendationCount }} commendations that are being counted toward RISE awards.</p>
<h2>Your progress</h2>
{% for i in milestoneProgress %}

    {% if i.percentage == 100 %}
        <div>
            <h3>{{i.type}}</h3>
            <p>{% if request.user.is_caregiver %}{{ student.user.first_name }} has {% else %}You have{% endif %} achieved this RISE award! Congratulations 🎉</p>
            <div class="barContainer">
                <div class="bar" style="width: 100%;"></div>
            </div>
        </div>
    {% else %}
        <div>
            <h3>{{i.type}}</h3>
            <p>{% if request.user.is_caregiver %}{{ student.user.first_name }} has {% else %}You have{% endif %} received {{commendationCount}}/{{i.value}} commendations needed to achieve this RISE award. Only {{i.remaining}} to go!</p>
            <div class="barContainer">
                <div class="bar" style="width: {{i.percentage}}%;"></div>
            </div>
        </div>
    {% endif %}
{% endfor %}
{% endblock content %}

commendations/templates/commendations/my_commendations.html
{% extends 'base.html' %}
{% load static %}

{% comment %} HTML title {% endcomment %}
{% block title %}My Commendations{% endblock title %}
{% comment %} Meta description {% endcomment %}
{% block description %}{% endblock description %}

{% comment %} Content that goes in the HTML head {% endcomment %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'commendations/my_commendations.min.css' %}">
{% endblock head %}

{% comment %} H1 at top of page, page title {% endcomment %}
{% block headerText %}My Commendations{% endblock headerText %}

{% comment %} Main content {% endcomment %}
{% block content %}
<p>
    To view more information about individual commendations click on the row in the table.
    <br>
    <br>
    {% if commendationsSince|length > 1 %}
        {% if request.user.is_caregiver %}{{ student.user.first_name }} has {% else %}You have{% endif %} have received new {{commendationsSince|length}} commendations since you last logged in.
        <br>
    {% elif commendationsSince|length == 1 %}
        {% if request.user.is_caregiver %}{{ student.user.first_name }} has {% else %}You have{% endif %} have received new {{commendationsSince|length}} commendation since you last logged in.
        <br>

    {% endif %}
    {% if request.user.is_caregiver %}{{ student.user.first_name }} has {% else %}You have{% endif %} have received {{commendations|length}} commendations in total.
</p>

<table id="myCommendations">
    <tr>
        <th>Type</th>
        <th>Date</th>
        <th>Reason</th>
    </tr>
    {% for commendation in commendations %}
        {% comment %} CommendationsSince is a set of new commendations, if the commendation is in commendationsSince then it should have the newCommendation class {% endcomment %}
        {% if commendation in commendationsSince %}
            <tr onclick="window.location.href='/commendations/detail/{{commendation.id}}'" class="newCommendation">
                <td class="Ctype">{{commendation.get_commendation_type_display}}</td>
                <td class="Cdata">{{ commendation.date_time|date:"F j, Y" }}</td>
                <td class="Creason">{{commendation.reason}}</td>
            </tr>
        {% else %}
            <tr onclick="window.location.href='/commendations/detail/{{commendation.id}}'">
                <td class="Ctype">{{commendation.get_commendation_type_display}}</td>
                <td class="Cdata">{{ commendation.date_time|date:"F j, Y" }}</td>
                <td class="Creason">{{commendation.reason}}</td>
            </tr>
        {% endif %}
    {% endfor %}
</table>
{% endblock content %}